// Date: 11/10/2011 12:37:43 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package justintib.quidcraft;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelBludger extends ModelBase
{
      //fields
    ModelRenderer Shape1;
      
      public ModelBludger()
      {
        Shape1 = new ModelRenderer(this, 0, 0);
        Shape1.addBox(0F, 0F, 0F, 5, 5, 5);
        Shape1.setRotationPoint(-2F, -5F, -2F);
        setRotation(Shape1, 0F, 0F, 0F);
      }
      @Override
      public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
      {
        //super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        Shape1.render(f5);
      }
      
      private void setRotation(ModelRenderer model, float x, float y, float z)
      {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
      }
}
