   // Date: 11/10/2011 11:41:39 AM
   // Java generated by Techne
   // This is the first stage to more output options
   // and therefore a very basic Render-File
   // I hope it will be useful, in any case, leave
   // feedback so I can improve on it
   // - ZeuX
   package justintib.quidcraft;
   import net.minecraft.client.model.ModelBase;
import net.minecraft.client.renderer.entity.Render;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

import org.lwjgl.opengl.GL11;

import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;
@SideOnly(Side.CLIENT)
   public class RenderBroom extends Render
   {
       public RenderBroom(ModelBroom model, float f)
       {
    	   this.shadowSize = f;
    	   this.modelBroom = model;
       }

       public void renderBroom(EntityBroom entitybroom, double d, double d1, double d2,
               float f, float f1)
       {
    	   GL11.glPushMatrix();
           GL11.glTranslatef((float)d, (float)d1+1.0F, (float)d2);
          //Added the following:
           GL11.glRotatef(180F - f, 0.0F, 1.0F, 0.0F);
           float f2 = (float)entitybroom.getTimeSinceHit() - f1;
           float f3 = (float)entitybroom.getDamageTaken() - f1;
           if(f3 < 0.0F)
           {
               f3 = 0.0F;
           }
           if(f2 > 0.0F)
           {
               GL11.glRotatef(((MathHelper.sin(f2) * f2 * f3) / 10F) * (float)entitybroom.getForwardDirection(), 1.0F, 0.0F, 0.0F);
           }     
           this.loadTexture("/terrain.png");
           float f4 = 0.75F;
           GL11.glScalef(f4, f4, f4);
           GL11.glScalef(1.0F / f4, 1.0F / f4, 1.0F / f4);
           //End of adding
           this.loadTexture("/skins/BroomSkin.png");
           GL11.glScalef(-1F, -1F, 1.0F);
           modelBroom.render(entitybroom, 0.0F, 0.0F, -0.1F, 0.0F, 0.0F, 0.0625F);
           GL11.glPopMatrix();
       }
@Override
       public void doRender(Entity entity, double d, double d1, double d2, float f, float f1)
       {
    	   this.renderBroom((EntityBroom)entity, d, d1, d2, f, f1);
       }
       
       protected ModelBase modelBroom;
   }

