   // Date: 11/10/2011 11:41:39 AM
   // Java generated by Techne
   // This is the first stage to more output options
   // and therefore a very basic Render-File
   // I hope it will be useful, in any case, leave
   // feedback so I can improve on it
   // - ZeuX
   package justintib.quidcraft;
   import net.minecraft.client.model.ModelBase;
import net.minecraft.client.renderer.entity.Render;
import net.minecraft.entity.Entity;

import org.lwjgl.opengl.GL11;

import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;
@SideOnly(Side.CLIENT)
   public class RenderBroom extends Render
   {

       public RenderBroom(ModelBroom model, float f)
       {
    	   this.shadowSize = f;
    	   this.modelBroom = model;
       }

       public void renderBroom(EntityBroom entitybroom, double d, double d1, double d2,
               float f, float f1)
       {
    	   GL11.glPushMatrix();
           GL11.glTranslatef((float)d, (float)d1+1.0F, (float)d2);
           //float yaw = 0F;
           //float pitch = 0F;
           //if(entitybroom.riddenByEntity != null)
        	//   yaw = (-1)*entitybroom.riddenByEntity.rotationYaw;
           //else
        	//   yaw = entitybroom.rotationYaw;
           
           //pitch = (float)entitybroom.motionY*(-50F);
           
          // GL11.glRotatef(yaw, 0.0F, 1.0F, 0.0F);
          // GL11.glRotatef(pitch, 1.0F, 0.0F, 0.0F);
           
           this.loadTexture("/skins/BroomSkin.png");
           GL11.glScalef(-1F, -1F, 1.0F);
           modelBroom.render(entitybroom, 0.0F, 0.0F, -0.1F, 0.0F, 0.0F, 0.0625F);
           GL11.glPopMatrix();
       }
@Override
       public void doRender(Entity entity, double d, double d1, double d2,
               float f, float f1)
       {
    	   renderBroom((EntityBroom)entity, d, d1, d2, f, f1);
       }
       
       protected ModelBase modelBroom;
   }

